### ISSUE TITLE
Highlight cases where unintended uses of path signals are causing problems

### ISSUE THREAD

**Issue by tfpauly** [intarchboard/draft-path-signals-collaboration#4]
Clients and networks have evolved their interaction without being based on intent and trust. Too many assumptions have been made. This ends up having several negative effects:
- Ossifying protocols by introducing unintended parties that may not be updating
- Creating systemic incentives against deploying more secure or private versions of protocols
- Gaps and flaws in network enforcement, and double standards
- Difficulty for clients to control identifiers or trust the network entities without explicit communication

We can catalog some instances of where this is breaking down, by breaking down:
- Feature intent
- Network use beyond intent (filtering)
- Flaws in unintended use
- Harm to protocol evolution

Examples include:
- DNS / Name Filtering
- TLS SNI / Name Filtering
- MAC Address / Access Control
- HTTP cleartext / Captive Portal
- DNS / Zero-rating and splitting

**Comment by mirjak** [comment]
It's important to keep in mind why these things are used: a) because they just could be used and b) because it was the cheapest and fastest option to fix a problem.

I think the important point is that while we acknowledge that is was a mistake to spread certain information without protection, we also need to work on solution for the problem these deployed mechanism address. These solution will like be more expensive and "complicated" (multiple parties need to cooperate to make it work) but hopefully also architecturally cleaner and therefore more future proof/more evolvable.
